### ISSUE TITLE
Propuesta de Reorganización de RubyPerú

### ISSUE THREAD

**Issue by frodsan** [rubyperu/rubyperu.github.com#20]
Sólo para tomar notas ...

**Comment by goddamnhippie** [comment]
Retomando esto con @kandra

**Comment by kandra** [comment]
Algunas ideas:
* Coordinador de Medios de Comunicación: @frecaze (Freddy Cahuas)
* Coordinador de Eventos y Reuniones: @kandra (Karen Da Cruz)

Algunas preguntas sobre estos roles:
Coordinador de Generación de Contenido.
* Que es lo que generariamos de contenido? Material educativo? Hangouts? Screencasts? Blogposts? Curacion de contenido? Peer programming?
* Podriamos empezar a incluir material de introduccion a Ruby para las personas que recien empiezan, que creo que es importante porque la mayoria de las personas que estan viniendo a la comunidad no están muy familiarizadas y están dando sus primeros pasos. Si esto se logra recopilando material ya existente, es también una opción.
* Esto se haria actualizando los recursos de ruby.pe de Aprende Ruby
![screen shot 2016-07-19 at 4 53 45 pm](https://cloud.githubusercontent.com/assets/1261833/16967940/68e855f2-4dd1-11e6-99e5-2a01e78d5127.png)

Coordinador de Financiamiento (En un futuro).
* Creo que es importante el financiamiento... pero más importante aún es saber para qué queremos el dinero. Antes de saber qué tipos de eventos queremos hacer... deberiamos pensar cuales son las metricas que definiran nuestro exito. Voy a ver si trabajo algunas ideas y comparto luego. 
* Por lo pronto tengo un plan de sponsors en draft: https://docs.google.com/document/d/139tE8-09uRpEdLiHCMnn8ZwFL5HGOISEM-MZHK1iwMM/edit?usp=sharing

**Comment by KattyaCuevas** [comment]
@kandra esto está desactualizado, cierro el issue o lo usamos para definir cómo puede ayudar la comunidad? Por ejemplo, el proceso de @luciagirasoles

**Comment by beathyate** [comment]
@kandra @KattyaCuevas me parece que hay que cerrar el issue.
