### ISSUE TITLE
Agregar link a Slack

### ISSUE THREAD

**Issue by goddamnhippie** [rubyperu/rubyperu.github.com#26]

**Comment by willywg** [comment]
@goddamnhippie quizá puedas automatizar el registro a Slack con https://github.com/outsideris/slack-invite-automation

**Comment by goddamnhippie** [comment]
hola @willywg gracias, si Freddy ya creó el sitio, es acá: http://bit.ly/rubyperu-slack
Me refería a agregar ese link en la web.

**Comment by kandra** [comment]
https://github.com/rubyperu/rubyperu.github.com/pull/28
cc: @goddamnhippie

**Comment by goddamnhippie** [comment]
Cerrado en #28
