### ISSUE TITLE
Actualizar la seccion Aprende Ruby en la web

### ISSUE THREAD

**Issue by kandra** [rubyperu/rubyperu.github.com#27]
![screen shot 2016-07-19 at 4 53 45 pm](https://cloud.githubusercontent.com/assets/1261833/16968075/30c277d8-4dd2-11e6-8c8b-b313cdb176bc.png)

Agregar nuevos recursos, herramientas online, etc.

**Comment by joelibaceta** [comment]
Cerrado debido a que hay un nuevo diseño en camino #35
