### ISSUE TITLE
Update broken links

### ISSUE THREAD

**Issue by KattyaCuevas** [rubyperu/rubyperu.github.com#33]
- [ ] Working with Rails
- [ ] Aprende a programar
- [x] Quitar Google+
- [x] Agregar nuestra de youtube
- [x] Agregar la pagina de meetup

**Comment by joelibaceta** [comment]
@KattyaCuevas ¿Cuales serian los nuevos links de Working with Rails y Aprende a programar?

**Comment by KattyaCuevas** [comment]
@joelibaceta parte de este PR es buscar nuevos links con tutoriales **en español** más actualizados y en el caso de no encontrar poner el link a la documentación oficial.

**Comment by joelibaceta** [comment]
Cerrado debido a que hay un nuevo diseño en camino #35
