### ISSUE TITLE
Actualizar diseño

### ISSUE THREAD

**Issue by KattyaCuevas** [rubyperu/rubyperu.github.com#35]

**Comment by joelibaceta** [comment]
@KattyaCuevas hay alguna propuesta de diseño ? o ese seria el primer paso?

**Comment by KattyaCuevas** [comment]
@joelibaceta el primer paso será presentar una propuesta de diseño

**Comment by joelibaceta** [comment]
Related https://github.com/rubyperu/rubyperu.github.com/pulls
